// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID           string  `json:"id"`
	CompanyCd    int     `json:"companyCD"`
	RrCd         int     `json:"rrCD"`
	CompanyName  string  `json:"companyName"`
	CompanyNameK *string `json:"companyNameK"`
	CompanyNameH *string `json:"companyNameH"`
	CompanyNameR *string `json:"companyNameR"`
	CompanyURL   *string `json:"companyURL"`
	CompanyType  *int    `json:"companyType"`
	EStatus      *int    `json:"eStatus"`
	ESort        *int    `json:"eSort"`
}

type Join struct {
	LineCd     int `json:"lineCD"`
	StationCd1 int `json:"stationCD1"`
	StationCd2 int `json:"stationCD2"`
}

type Line struct {
	ID        string   `json:"id"`
	LineCd    int      `json:"lineCD"`
	CompanyCd int      `json:"companyCD"`
	LineName  string   `json:"lineName"`
	LineNameK *string  `json:"lineNameK"`
	LineNakeH *string  `json:"lineNakeH"`
	LineType  *string  `json:"lineType"`
	Lon       *float64 `json:"lon"`
	Lat       *float64 `json:"lat"`
	Zoom      *int     `json:"zoom"`
	EStatus   *int     `json:"e_status"`
	ESort     *int     `json:"e_sort"`
}

type Station struct {
	StationCd   int     `json:"stationCD"`
	StationGcd  int     `json:"stationGCD"`
	StationName string  `json:"stationName"`
	LineCd      int     `json:"lineCD"`
	LineName    *string `json:"lineName"`
	Address     *string `json:"address"`
}

type StationConn struct {
	Station         *Station   `json:"station"`
	TransferStation []*Station `json:"transferStation"`
	BeforeStation   *Station   `json:"beforeStation"`
	AfterStation    *Station   `json:"afterStation"`
}
