// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Company struct {
	ID           string  `json:"id"`
	CompanyCd    int     `json:"companyCD"`
	RrCd         int     `json:"rrCD"`
	CompanyName  string  `json:"companyName"`
	CompanyNameK *string `json:"companyNameK"`
	CompanyNameH *string `json:"companyNameH"`
	CompanyNameR *string `json:"companyNameR"`
	CompanyURL   *string `json:"companyURL"`
	CompanyType  *int    `json:"companyType"`
	EStatus      *int    `json:"eStatus"`
	ESort        *int    `json:"eSort"`
}

type Join struct {
	LineCd     int `json:"lineCD"`
	StationCd1 int `json:"stationCD1"`
	StationCd2 int `json:"stationCD2"`
}

type Line struct {
	ID         string   `json:"id"`
	LineCd     int      `json:"lineCD"`
	CompanyCd  int      `json:"companyCD"`
	LineName   string   `json:"lineName"`
	LineNameK  *string  `json:"lineNameK"`
	LineNakeH  *string  `json:"lineNakeH"`
	LineColorC *string  `json:"lineColorC"`
	LineColorT *string  `json:"lineColorT"`
	LineType   *string  `json:"lineType"`
	Lon        *float64 `json:"lon"`
	Lat        *float64 `json:"lat"`
	Zoom       *int     `json:"zoom"`
	EStatus    *int     `json:"e_status"`
	ESort      *int     `json:"e_sort"`
}

type Station struct {
	StationCd    int        `json:"stationCD"`
	StationGcd   int        `json:"stationGCD"`
	StationName  string     `json:"stationName"`
	StationNameK *string    `json:"stationNameK"`
	StationNameR *string    `json:"stationNameR"`
	LineCd       int        `json:"lineCD"`
	PrefCd       *int       `json:"prefCD"`
	Post         *string    `json:"post"`
	Address      *string    `json:"address"`
	Lon          *float64   `json:"lon"`
	Lat          *float64   `json:"lat"`
	OpenYmd      *time.Time `json:"open_ymd"`
	CloseYmd     *time.Time `json:"close_ymd"`
	EStatus      *int       `json:"eStatus"`
	ESort        *int       `json:"eSort"`
}

type StationConn struct {
	Station         *Station   `json:"station"`
	TransferStation []*Station `json:"transferStation"`
	BeforeStation   []*Station `json:"beforeStation"`
	AfterStation    []*Station `json:"afterStation"`
}
